# Generated by Django 4.0 on 2022-01-17 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='vehicle model')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('chasis_no', models.CharField(max_length=100, verbose_name='chasis number')),
                ('engine_no', models.CharField(max_length=100, verbose_name='engine number')),
                ('reg_no', models.CharField(max_length=100, unique=True, verbose_name='registration number')),
                ('key_no', models.CharField(blank=True, default='None', max_length=20, verbose_name='key number')),
                ('battery_no', models.CharField(max_length=100, verbose_name='battery number')),
                ('mfd_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)], verbose_name='mfd year')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('chasis_no', 'engine_no'), name='unique_vehicle'),
        ),
    ]
