# Generated by Django 4.0 on 2022-01-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('purchase_date', models.DateField(verbose_name='purchase date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('vendor_name', models.CharField(max_length=200, verbose_name='vendor name')),
                ('vendor_address', models.TextField(max_length=300, verbose_name='vendor address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
