# Generated by Django 4.0 on 2022-01-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='scheme_id',
            new_name='scheme',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
